import { useState } from "react";
import { apiRequest } from "../../utils/api";
import useRemote from "../../utils/useRemote";
import { Notice, Pagination } from "./AdminPage";
const LABELS = { draft: "Սևագիր", preparing: "Հասցեատերերը հավաքվում են", queued: "Ուղարկման հերթում", completed: "Ավարտված", cancelled: "Չեղարկված", sent: "Ուղարկված", pending: "Սպասող", sending: "Ուղարկվում է", failed: "Սխալ", uncertain: "Առաքումը պետք է ստուգել", skipped: "Բաց թողնված" };
export default function AdminBroadcasts() {
    const [subject, setSubject] = useState(""), [text, setText] = useState(""), [html, setHtml] = useState(""), [revision, setRevision] = useState(0), [page, setPage] = useState(1), [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState("");
    const [selected, setSelected] = useState(null), [deliveries, setDeliveries] = useState(null);
    const state = useRemote(`/admin/broadcasts?page=${page}`, revision);
    async function task(fn) { setBusy(true); setError(""); setMessage(""); try { await fn(); } catch (error) { setError(error.message); } finally { setBusy(false); } }
    async function preview() { await task(async () => { const result = await apiRequest("/admin/broadcasts/preview", { method: "POST", body: JSON.stringify({ subject, text }) }); setHtml(result.html); }); }
    async function save(event) { event.preventDefault(); await task(async () => { await apiRequest("/admin/broadcasts", { method: "POST", body: JSON.stringify({ subject, text }) }); setSubject(""); setText(""); setHtml(""); setMessage("Նամակը պահպանված է որպես սևագիր։ Ուղարկելու համար հաստատեք ցանկից։"); setRevision(value => value + 1); }); }
    async function confirmSend() { await task(async () => { await apiRequest(`/admin/broadcasts/${selected._id}/send`, { method: "POST", body: JSON.stringify({ confirm: true }) }); setSelected(null); setRevision(value => value + 1); setMessage("Նամակը ավելացվել է ուղարկման հերթին։"); }); }
    async function cancel(row) { await task(async () => { await apiRequest(`/admin/broadcasts/${row._id}/cancel`, { method: "POST" }); setRevision(value => value + 1); }); }
    async function inspect(row, targetPage = 1) { await task(async () => { const result = await apiRequest(`/admin/broadcasts/${row._id}/deliveries?page=${targetPage}`); setDeliveries({ ...result, broadcast: row }); }); }
    return <><Notice state={state} /><div className="admin-toolbar"><span>{state.data?.recipients || 0} ակտիվ հասցեատեր</span><button disabled={busy} onClick={() => setRevision(value => value + 1)}>Թարմացնել կարգավիճակները</button>{state.data && !state.data.mailConfigured && <p>Ուղարկման համար լրացրեք SMTP կարգավորումները .env-ում։</p>}</div>{error && <p role="alert" className="admin-error">{error}</p>}{message && <p role="status" className="admin-success">{message}</p>}
        <section className="admin-panel"><h2>Նոր նամակ</h2><p>Ստացողները չեն տեսնի միմյանց email-ները։ Արգելափակված ու ջնջված հաշիվները չեն ստանա նամակը։</p><form className="admin-edit-form" onSubmit={save}><label>Վերնագիր<input value={subject} onChange={event => { setSubject(event.target.value); setHtml(""); }} required maxLength={150} /></label><label>Նամակի տեքստը<textarea value={text} onChange={event => { setText(event.target.value); setHtml(""); }} required maxLength={10000} rows={7} /></label><div className="admin-row-actions"><button type="button" disabled={busy || !subject.trim() || !text.trim()} onClick={preview}>Նախադիտել նամակը</button><button disabled={busy} className="admin-primary">Պահպանել սևագիրը</button></div></form>{html && <iframe className="broadcast-preview" title="Նամակի նախադիտում" srcDoc={html} sandbox="" />}</section>
        <div className="admin-table-wrap"><table><thead><tr><th>Նամակ</th><th>Կարգավիճակ</th><th>Ուղարկումներ</th><th>Գործողություններ</th></tr></thead><tbody>{state.data?.items.map(row => <tr key={row._id}><td>{row.subject}<small>{new Date(row.createdAt).toLocaleDateString("hy-AM")}</small></td><td><span className="admin-status">{LABELS[row.status]}</span></td><td>{row.counts.sent || 0} / {row.total}<small>Սխալ՝ {row.counts.failed || 0} · Ստուգել՝ {row.counts.uncertain || 0}</small></td><td><div className="admin-row-actions">{row.status === "draft" && <button disabled={busy || !state.data.mailConfigured} onClick={() => setSelected(row)}>Ուղարկել բոլորին</button>}{["draft", "queued"].includes(row.status) && <button disabled={busy} onClick={() => cancel(row)}>Չեղարկել</button>}<button disabled={busy} onClick={() => inspect(row)}>Առաքումների ցանկ</button></div></td></tr>)}</tbody></table></div><Pagination page={page} setPage={setPage} total={state.data?.total || 0} />
        {selected && <div className="admin-modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="broadcast-confirm-title"><h2 id="broadcast-confirm-title">Հաստատե՞լ ուղարկումը</h2><strong>{selected.subject}</strong><p className="admin-message-body">{selected.text}</p><p>Նամակը կուղարկվի բոլոր {state.data?.recipients || 0} ակտիվ գրանցված հաշիվներին։</p><div className="admin-row-actions"><button disabled={busy} onClick={() => setSelected(null)}>Չեղարկել</button><button className="admin-primary" disabled={busy} onClick={confirmSend}>Հաստատել և ուղարկել</button></div></section></div>}
        {deliveries && <div className="admin-modal-backdrop"><section className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="deliveries-title"><div className="admin-panel-heading"><h2 id="deliveries-title">{deliveries.broadcast.subject}</h2><button onClick={() => setDeliveries(null)} aria-label="Փակել">×</button></div><div className="admin-table-wrap"><table><thead><tr><th>Email</th><th>Կարգավիճակ</th></tr></thead><tbody>{deliveries.items.map(row => <tr key={row._id}><td>{row.email}</td><td>{LABELS[row.status]}<small>{row.error}</small></td></tr>)}</tbody></table></div><Pagination page={deliveries.page} setPage={value => inspect(deliveries.broadcast, value)} total={deliveries.total} /></section></div>}
    </>;
}
